version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-news-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
